apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |-
    # global config
    global:
      scrape_interval: 15s 
      evaluation_interval: 15s 

    scrape_configs:
    - job_name: 'tyhdc'
      static_configs:
        - targets: ['10.1.0.201:9100','10.1.0.202:9100','10.1.0.203:9100']
    - job_name: 'dev-ws'
      static_configs:
        - targets: ['10.1.0.200:9100']
    - job_name: 'minecraft'
      static_configs:
        - targets: ['10.0.0.6:9985']
        - targets: ['10.0.0.6:9940']
        - targets: ['10.1.5.1:9940']
        - targets: ['10.1.0.200:9940']