apiVersion: v1
kind: Service
metadata:
  name: murchace
  namespace: murchace
  annotations:
    external-dns.alpha.kubernetes.io/hostname: murchace.svc.ddlia.com
    io.cilium/lb-ipam-pools: "internal"
spec:
  selector:
    app: murchace
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000