apiVersion: v1
kind: Service
metadata:
  name: reflet-service
  namespace: reflet
  annotations:
    external-dns.alpha.kubernetes.io/hostname: looking-glass.k8s.ddlia.com
spec:
  selector:
    vm.kubevirt.io/name: dev
  type: LoadBalancer
  ports:
    - name: ssh
      port: 22
      targetPort: 22
    - name: bgp
      port: 179
      targetPort: 179
    - name: http
      port: 80
      targetPort: 80