apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: metallb-system
spec:
  addresses:
  - 10.88.0.0/16
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-ipv6
  namespace: metallb-system
spec:
  addresses:
  - <NTT-NGN RA Prefix>:feed::/112
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - default-ipv6