apiVersion: "cilium.io/v2"
kind: CiliumLoadBalancerIPPool
metadata:
  name: ipv4-bgp-pool
spec:
  blocks:
    - cidr: "10.88.0.0/16"

---

apiVersion: "cilium.io/v2"
kind: CiliumLoadBalancerIPPool
metadata:
  name: ipv6-ndp-pool-gua
spec:
  blocks:
    - cidr: "<NGN-Prefix>::beef:0/112"
    
---

apiVersion: "cilium.io/v2"
kind: CiliumLoadBalancerIPPool
metadata:
  name: ipv6-ndp-pool-ula
spec:
  blocks:
    - cidr: "fd00:20::beef:0/112"
