apiVersion: v1
kind: Service
metadata:
  name: pihole-v6
  labels:
    app: pihole
    io.cilium/lb-pool: ula
  namespace: pi-hole
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ns0.svc.ddlia.com
    external-dns.alpha.kubernetes.io/provider: "pihole"
    io.cilium/lb-ipam-ips: "fd00:20::beef:ffff"
spec:
  selector:
    app: pihole
  type: LoadBalancer
  ipFamilies:
    - IPv6
  ipFamilyPolicy: SingleStack
  ports:
    - name: dns-tcp
      protocol: TCP
      port: 53
      targetPort: 53
    - name: dns-udp
      protocol: UDP
      port: 53
      targetPort: 53
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443