apiVersion: v1
kind: Service
metadata:
  name: pihole
  namespace: pi-hole
  labels:
    announce: bgp-v4
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ns0.svc.ddlia.com
    io.cilium/lb-ipam-ips: "10.88.254.254"
spec:
  selector:
    app: pihole
  type: LoadBalancer
  ports:
    - name: dns-tcp
      protocol: TCP
      port: 53
      targetPort: 53
    - name: dns-udp
      protocol: UDP
      port: 53
      targetPort: 53
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
