apiVersion: v1
kind: Service
metadata:
  name: dev-service
spec:
  externalTrafficPolicy: Cluster
  selector:
    app: dev
  type: LoadBalancer
  ports:
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 22
