apiVersion: v1
kind: Service
metadata:
  name: dev-service
  labels:
    app: dev
spec:
  selector:
    app: dev
  type: LoadBalancer
  ports:
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 22
