apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: dev
  labels:
    kubevirt.io/os: linux
spec:
  running: true
  template:
    spec:
      domain:
        cpu:
          cores: 1
        devices:
          disks:
          - disk:
              bus: virtio
            name: disk0
          - cdrom:
              bus: sata
              readonly: true
            name: cloudinitdisk
        machine:
          type: q35
        resources:
          requests:
            memory: 512M
      volumes:
      - name: disk0
        persistentVolumeClaim:
          claimName: dev-trixie-pvc
      - cloudInitNoCloud:
          userData: |
            #cloud-config
            hostname: spr-dev
            ssh_pwauth: true
            disable_root: false
            chpasswd:
              list: |
                root:password
              expire: False
        name: cloudinitdisk