apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: murchace-db
  namespace: murchace
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi