apiVersion: v1
kind: Service
metadata:
  name: pihole
  namespace: pi-hole
  annotations:
    external-dns.alpha.kubernetes.io/hostname: pihole.k8s.ddlia.com
spec:
  selector:
    app: pihole
  type: LoadBalancer
  loadBalancerIP: 10.88.254.253
  ports:
    - name: dns-tcp
      protocol: TCP
      port: 53
      targetPort: 53
    - name: dns-udp
      protocol: UDP
      port: 53
      targetPort: 53
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
