apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudflare-external-dns
  namespace: cloudflare
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudflare-external-dns
rules:
  - apiGroups: [""]
    resources: ["services","pods"]
    verbs: ["get","watch","list"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get","watch","list"]
  - apiGroups: ["extensions","networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get","watch","list"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloudflare-external-dns-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cloudflare-external-dns
subjects:
- kind: ServiceAccount
  name: cloudflare-external-dns
  namespace: cloudflare
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-external-dns
  namespace: cloudflare
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: cloudflare-external-dns
  template:
    metadata:
      labels:
        app: cloudflare-external-dns
    spec:
      serviceAccountName: cloudflare-external-dns
      containers:
        - name: cloudflare-external-dns
          image: registry.k8s.io/external-dns/external-dns:v0.21.0
          args:
            - --source=service
            - --source=ingress
            - --domain-filter=ddlia.com
            - --domain-filter=technotut.net
            - --provider=cloudflare
            - --annotation-filter=external-dns.alpha.kubernetes.io/provider=cloudflare
            - --cloudflare-record-comment="provisioned by kubernetes-external-dns"
            - --log-level=debug
            - --policy=sync
          env:
            - name: CF_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflare-api-key
                  key: apiKey